server:
  port: 9000
spring:
  application:
    name: 3scale-groovy-broker
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
  main:
    show_banner: false
